import math

#We should have 2 * LOWER_THRESHOLD_ROOT < UPPER_THRESHOLD_ROOT
LOWER_THRESHOLD_ROOT = 0.2
LOWER_THRESHOLD_LEAF = 0.1
UPPER_THRESHOLD_ROOT = 0.5
UPPER_THRESHOLD_LEAF = 0.9
LEARNEDLLA_UPPER_THRESHOLD = 0.5
MEMORY_SCALE = math.ceil(3 / LEARNEDLLA_UPPER_THRESHOLD)
INF = 1e12